### PR TITLE
Make InlineFlowDefinition public

### PR DESCRIPTION
**Pull request by dee-kryvenko**
It is currently impossible to extend this class

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by daniel-beck** [comment]
Not sure I want to have to maintain this as stable API for downstream consumers. What's the use case?

**Comment by dee-kryvenko** [comment]
No matter the use case - no one is able to inherit and extend this class. Making the class public does not necessarily make you consider it a public API. It should be a matter of conventions and documentation, not a physical limit. Why don't you leave this decision and risks to the consumer... Currently you leave me with no choice but to write a complete replacement from scratch. How is it better for me?

**Review by basil — CHANGES_REQUESTED** [review]
See Item 19 of _Effective Java_ by Joshua Bloch ("Design and document for inheritance or else prohibit it"):

> **The _only_ way to test a class designed for inheritance is to write subclasses.** […] Experience shows that three subclasses are usually sufficient to test an extendable class. One or more of these subclasses should be written by someone other than the superclass author.

> When you design for inheritance a class that is likely to achieve wide use, realize that you are committing _forever_ to the self-use patterns that you document and to the implementation decisions implicit in its protected methods and fields. These commitments can make it difficult or impossible to improve the performance or functionality of the class in a subsequent release. **Therefore, you must test your class by writing subclasses _before_ you release it.**

(Emphasis _not_ mine.)

This class is not designed and documented for inheritance; therefore, prohibiting inheritance is reasonable. Redesigning this class for inheritance is not out of the question, but (as described above) it carries risks for maintainers. These risks can be mitigated by validating and testing the design through the implementation of concrete subclasses. Implementing a concrete subclass demonstrates that the extensible design works in practice, and failing to do so is tantamount to implementing a change without testing. The maintainers cannot commit to accepting and maintaining such changes.

I would suggest that you provide an example subclass, explaining the use case and how the newly-extensible design can be utilized by the subclass in order to accommodate that use case. If the use case is valid and the subclass demonstrates that the extensible design can be cleanly utilized, then I see no reason why the maintainers would not accept this PR.

**Comment by dee-kryvenko** [comment]
I would like to start with reminding you why Open Source exists. It is so that we all can enjoy reusing each other's work and not having to start from scratch every time we need to make something. Instead - we build on top of each other work thus building bigger and better things together that not a single one of us would be able to build alone otherwise.

I completely understand where Joshua Bloch is coming from. What he is talking about - is common sense. If the intended use case of the class you are designing is to be inherited - inheritance is a feature of such class thus it must be tested. There's no disagreement there. Although his conclusion on the reasoning sound rather barbaric.

Where I am not following you on is - not only I can't extend this class, I can't even import it. I can't do anything with it without falling back to the slow and clumsy reflection tools. It is one thing to say that the class is not intended to be inherited, but "prohibiting" it via the class access modifier is a totally different beast due to unintended consequences of it. Let's say I am not extending the class in the traditional sense of it - maybe I just want to work around certain issue without functional modifications. Maybe - add some logging or instrument with a telemetry probe.

Let me make an example. In Go, if something doesn't work to my liking - I can just fork, make a change, and even in a so often case of mainstream maintainers not accepting or delaying the PR - I can start using it right away. Go modules dependency management built exactly for that - I can just start using my fork, no questions asked, and I don't need any infrastructure for it (or anyone's permission). Of course doing that is a big liability on my part, as I am opening doors for troubles later on as the mainstream will move forward. But guess what - that responsibility is on me! Why should anyone else decide for me should I be able to shoot my own leg or not? Physically preventing me from inheriting your class feels rather... tyrannical.

Java does not have such reusability utility built-in. Producing a maven artifact and hosting it somewhere is a hassle. On the other side of that coin is you - mainstream maintainers - who restricted the use of this class.

For the end user of your code - you basically reduced reusability of your work to a zero. I can't just copy your code to my private codebase due to the license limitations, I can't "patch" the class through the inheritance, I can't easily fork it to reuse from there - you are leaving me with no option but to start from scratch as if your work never existed for me. There might be multiple perspectives on the same issue. I am sure Joshua Bloch was so focused on code smell issues that he might just overlooked other aspects of our OSS community needs. Or was he ever had OSS community needs in mind?

**Comment by daniel-beck** [comment]
> I can't just copy your code to my private codebase due to the license limitations

What specifically are your concerns about the MIT license?

**Pull request closed without merging**
