### PR TITLE
JENKINS-66041: Fetch marker file and make it available via global var `markerFile`

### PR DESCRIPTION
**Pull request by dee-kryvenko**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

This change enables inline-pipeline plugin to read the marker file from repository and allow to access it's content as string in the `Jenkinsfile`.

This also adds `SCMRevisionAction` early in the build which might be needed by some other plugins.

See https://issues.jenkins.io/browse/JENKINS-66041.

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
This approach stores the `markerFileContent` as part of the branch job configuration, essentially reconfiguring the build step. This can cause problems with changing markerfile contents over time, while multiple builds are running in parallel.

(FWIW I am not yet decided whether this would be a reasonable feature if implemented as opt-in, or whether that option isn't worth it and it should always retrieve the file contents.)

**Comment by dee-kryvenko** [comment]
@daniel-beck what would be the correct approach to store and retrieve the data?

**Comment by daniel-beck** [comment]
@dee-kryvenko Look into defining an `Action` subtype that holds the value you want, and attach it to the build. Then look up your `Action` in your build when using the variable.

**Comment by dee-kryvenko** [comment]
@daniel-beck - thanks, I think I got it now.

**Pull request closed without merging**
